### ISSUE TITLE
Update to pm5

### ISSUE THREAD

**Issue by ghost** [ColinHDev/CPlot#35] opened 2022-07-21 12:47 UTC
Please update to pm5

**Comment by supercrafter333** [comment] 2022-07-21 12:50
Duplicate of #25

**Comment by ColinHDev** [comment] 2022-07-21 17:01
I plan to make a `pm5` branch, not because I consider actively supporting this version, but to fix bugs like #37 so I don't forget to fix these later on

**Closed as completed** 2022-07-21 17:02 UTC
Labels: Type: Support Request
