### ISSUE TITLE
Some Commands are Broken oder Missing

### ISSUE THREAD

**Issue by note3crafter** [ColinHDev/CPlot#82] opened 2023-06-14 10:43 UTC
Thats happening when i type -> " /p visit"

PocketMine-MP Crash Dump Wed Jun 14 12:37:42 CEST 2023

PocketMine-MP version: 5.1.2 [Protocol 589]
Git commit: 7cd317bf398a017f7c690a475c5a67650c610323
PHP version: 8.2.6
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: CPlot

Error: Unhandled async exception: Position world is null or has been unloaded
File: plugins/CPlot_dev-development (2).phar/src/_e267b83df3ebb755c285_SOFe/AwaitGenerator/Await
Line: 587
Type: _e267b83df3ebb755c285_SOFe\AwaitGenerator\AwaitException
Backtrace:
#0 plugins/CPlot_dev-development (2).phar/src/_e267b83df3ebb755c285_SOFe/AwaitGenerator/Await(334): _e267b83df3ebb755c285_SOFe\AwaitGenerator\Await->reject(object pocketmine\utils\AssumptionFailedError#270908)
#1 plugins/CPlot_dev-development (2).phar/src/_e267b83df3ebb755c285_SOFe/AwaitGenerator/Await(317): _e267b83df3ebb755c285_SOFe\AwaitGenerator\Await->wakeup(object Closure#269126)
#2 plugins/CPlot_dev-development (2).phar/src/_e267b83df3ebb755c285_SOFe/AwaitGenerator/Await(552): _e267b83df3ebb755c285_SOFe\AwaitGenerator\Await->wakeupFlat(object Closure#269126)
#3 plugins/CPlot_dev-development (2).phar/src/_e267b83df3ebb755c285_SOFe/AwaitGenerator/AwaitChild(52): _e267b83df3ebb755c285_SOFe\AwaitGenerator\Await->recheckPromiseQueue(object _e267b83df3ebb755c285_SOFe\AwaitGenerator\AwaitChild#270842)
#4 plugins/CPlot_dev-development (2).phar/src/_e267b83df3ebb755c285_SOFe/AwaitGenerator/Await(570): _e267b83df3ebb755c285_SOFe\AwaitGenerator\AwaitChild->resolve(object ColinHDev\CPlot\plots\Plot#270829)
#5 plugins/CPlot_dev-development (2).phar/src/_e267b83df3ebb755c285_SOFe/AwaitGenerator/Await(340): _e267b83df3ebb755c285_SOFe\AwaitGenerator\Await->resolve(object ColinHDev\CPlot\plots\Plot#270829)
#6 plugins/CPlot_dev-development (2).phar/src/_e267b83df3ebb755c285_SOFe/AwaitGenerator/Await(317): _e267b83df3ebb755c285_SOFe\AwaitGenerator\Await->wakeup(object Closure#270792)
#7 plugins/CPlot_dev-development (2).phar/src/_e267b83df3ebb755c285_SOFe/AwaitGenerator/Await(552): _e267b83df3ebb755c285_SOFe\AwaitGenerator\Await->wakeupFlat(object Closure#270792)
#8 plugins/CPlot_dev-development (2).phar/src/_e267b83df3ebb755c285_SOFe/AwaitGenerator/AwaitChild(52): _e267b83df3ebb755c285_SOFe\AwaitGenerator\Await->recheckPromiseQueue(object _e267b83df3ebb755c285_SOFe\AwaitGenerator\AwaitChild#270803)
#9 plugins/CPlot_dev-development (2).phar/src/_f4b6c816a256cd4954b0_poggit/libasynql/base/DataConnectorImpl(197): _e267b83df3ebb755c285_SOFe\AwaitGenerator\AwaitChild->resolve(array[0])
#10 plugins/CPlot_dev-development (2).phar/src/_f4b6c816a256cd4954b0_poggit/libasynql/base/DataConnectorImpl(174): _f4b6c816a256cd4954b0_poggit\libasynql\base\DataConnectorImpl::_f4b6c816a256cd4954b0_poggit\libasynql\base\{closure}(array[0], array[0])
#11 plugins/CPlot_dev-development (2).phar/src/_f4b6c816a256cd4954b0_poggit/libasynql/base/DataConnectorImpl(181): _f4b6c816a256cd4954b0_poggit\libasynql\base\DataConnectorImpl::_f4b6c816a256cd4954b0_poggit\libasynql\base\{closure}(object _f4b6c816a256cd4954b0_poggit\libasynql\result\SqlSelectResult#270830)
#12 plugins/CPlot_dev-development (2).phar/src/_f4b6c816a256cd4954b0_poggit/libasynql/base/DataConnectorImpl(239): _f4b6c816a256cd4954b0_poggit\libasynql\base\DataConnectorImpl::_f4b6c816a256cd4954b0_poggit\libasynql\base\{closure}(array[1])
#13 plugins/CPlot_dev-development (2).phar/src/_f4b6c816a256cd4954b0_poggit/libasynql/base/SqlThreadPool(111): _f4b6c816a256cd4954b0_poggit\libasynql\base\DataConnectorImpl->_f4b6c816a256cd4954b0_poggit\libasynql\base\{closure}(array[1])
#14 plugins/CPlot_dev-development (2).phar/src/_f4b6c816a256cd4954b0_poggit/libasynql/base/DataConnectorImpl(322): _f4b6c816a256cd4954b0_poggit\libasynql\base\SqlThreadPool->readResults(array[1])
#15 plugins/CPlot_dev-development (2).phar/src/_f4b6c816a256cd4954b0_poggit/libasynql/base/SqlThreadPool(64): _f4b6c816a256cd4954b0_poggit\libasynql\base\DataConnectorImpl->checkResults()
#16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): _f4b6c816a256cd4954b0_poggit\libasynql\base\SqlThreadPool->_f4b6c816a256cd4954b0_poggit\libasynql\base\{closure}()
#17 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#18 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#19 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1686739062.5738)
#20 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
#21 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[17] /home/CyberCraft/, string[25] /home/CyberCraft/plugins/)
#22 pmsrc/src/PocketMine(357): pocketmine\server()
#23 pmsrc(11): require(string[61] phar:///home/CyberCraft/PocketMine-MP.phar/src/PocketMine.php)

Code:
[578] 		$this->sleeping = true;
[579] 
[580] 		parent::reject($throwable);
[581] 		foreach($this->catches as $class => $onError){
[582] 			if($class === "" || is_a($throwable, $class)){
[583] 				$onError($throwable);
[584] 				return;
[585] 			}
[586] 		}
[587] 		throw new AwaitException("Unhandled async exception: {$throwable->getMessage()}", 0, $throwable);
[588] 	}
[589] 
[590] 	/**
[591] 	 * @internal This is implementation detail. Existence, signature and behaviour are semver-exempt.
[592] 	 */
[593] 	public function isSleeping() : bool{
[594] 		return $this->sleeping;
[595] 	}
[596] }

Loaded plugins:
CPlot development by ColinHDev for API(s) 5.0.0
CoreV7 7.1.1_BETA by TheNote/Rudolf2000/note3crafter, TheNote/Rudolf2000, tim03we, xxflow, Aneoxic, FleekRush, JackMD, LookItsAku, Philip, Hagnbrain, EnderDirt, Crasher508, MDevPmmP, jojoe77777, GamerMJay for API(s) 5.0.0
DevTools 1.17.0 by PocketMine Team for API(s) 5.0.0
EasyEdit 3.0.0 by platz1de for API(s) 5.0.0
MultiWorld 2.1.0-beta2 by CzechPMDevs, VixikCZ, fuyutsuki, kaliiks for API(s) 5.0.0
MysteryCrate 11.0.0 by JackMD, DaPigGuy, Crasher508, TheNote for API(s) 5.0.0
RegisterBlockDemoPM5 0.0.1 by  for API(s) 5.0.0
Secrets 1.0.0 by Crasher508 for API(s) 5.0.0
Shield 1.18.0 by JavierLeon9966 for API(s) 5.0.0
Slapper 3.0.0 by Vecnavium, jojoe77777 for API(s) 5.0.0
SlapperRotationV2 2.0.5 by xqwtxon for API(s) 5.0.0
Texter 4.2.0 by yuko fuyutsuki, mfmfnek0, onebone, ogiwara, Shootsta_ERU0531, Toganon, ShadowArt, Marron0421, No4NaMe, iteplenky, SuperYYT, SuperAdam47, minijaham, VicoSilalahi, TobyDev265, IvanCraft623 for API(s) 5.1.2
TopVoter 4.0.0 by SalmonDE, TheNote\RetroRolf for API(s) 5.0.0
VanillaElytra 1.13.0 by JavierLeon9966 for API(s) 5.0.0

**Comment by note3crafter** [comment] 2023-06-14 10:44
This was happening when i type /p clear on a claimed Plot but after restart is it normal?
![Screenshot 2023-06-14 124329](https://github.com/ColinHDev/CPlot/assets/38653750/010d86e0-f47f-429a-a5dc-d4613c49ea6f)

**Comment by note3crafter** [comment] 2023-06-14 10:47
This was happening when i type -> "/p boarder 1"
PocketMine-MP Crash Dump Wed Jun 14 12:45:47 CEST 2023

PocketMine-MP version: 5.1.2 [Protocol 589]
Git commit: 7cd317bf398a017f7c690a475c5a67650c610323
PHP version: 8.2.6
OS: Linux, linux

Error: No serializer registered for pocketmine\block\UnknownBlock with type ID 0
File: pmsrc/src/data/bedrock/block/convert/BlockObjectToStateSerializer
Line: 245
Type: pocketmine\data\bedrock\block\BlockStateSerializeException
Backtrace:
#0 pmsrc/src/data/bedrock/block/convert/BlockObjectToStateSerializer(203): pocketmine\data\bedrock\block\convert\BlockObjectToStateSerializer->serializeBlock(object pocketmine\block\UnknownBlock#247484)
#1 pmsrc/src/world/format/io/leveldb/LevelDB(201): pocketmine\data\bedrock\block\convert\BlockObjectToStateSerializer->serialize(int 0)
#2 pmsrc/src/world/format/io/leveldb/LevelDB(730): pocketmine\world\format\io\leveldb\LevelDB->serializeBlockPalette(object pocketmine\utils\BinaryStream#248407, object pocketmine\world\format\PalettedBlockArray#359876)
#3 pmsrc/src/world/World(1402): pocketmine\world\format\io\leveldb\LevelDB->saveChunk(int 10, int 15, object pocketmine\world\format\io\ChunkData#59534, int -1)
#4 pmsrc/src/world/World(1389): pocketmine\world\World->saveChunks()
#5 pmsrc/src/world/WorldManager(401): pocketmine\world\World->save(false)
#6 pmsrc/src/world/WorldManager(363): pocketmine\world\WorldManager->doAutoSave()
#7 pmsrc/src/Server(1789): pocketmine\world\WorldManager->tick(int 6000)
#8 pmsrc/src/Server(1671): pocketmine\Server->tick()
#9 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
#10 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[17] /home/CyberCraft/, string[25] /home/CyberCraft/plugins/)
#11 pmsrc/src/PocketMine(357): pocketmine\server()
#12 pmsrc(11): require(string[61] phar:///home/CyberCraft/PocketMine-MP.phar/src/PocketMine.php)

Code:
[236] 	 * @phpstan-param TBlockType $blockState
[237] 	 *
[238] 	 * @throws BlockStateSerializeException
[239] 	 */
[240] 	public function serializeBlock(Block $blockState) : BlockStateData{
[241] 		$typeId = $blockState->getTypeId();
[242] 
[243] 		$locatedSerializer = $this->serializers[$typeId] ?? null;
[244] 		if($locatedSerializer === null){
[245] 			throw new BlockStateSerializeException("No serializer registered for " . get_class($blockState) . " with type ID $typeId");
[246] 		}
[247] 
[248] 		/**
[249] 		 * TODO: there is no guarantee that this type actually matches that of $blockState - a plugin may have stolen
[250] 		 * the type ID of the block (which never makes sense, even in a world where overriding block types is a thing).
[251] 		 * In the future we'll need some way to guarantee that type IDs are never reused (perhaps spl_object_id()?)
[252] 		 *
[253] 		 * @var \Closure $serializer
[254] 		 * @phpstan-var \Closure(TBlockType) : Writer $serializer
[255] 		 */

**Comment by note3crafter** [comment] 2023-06-14 10:48
Command /p home [1,2,3...] missing or removed(but wye?)

**Comment by note3crafter** [comment] 2023-06-14 11:03
Command /p merge crashes 

PocketMine-MP Crash Dump Wed Jun 14 13:01:52 CEST 2023

PocketMine-MP version: 5.1.2 [Protocol 589]
Git commit: 7cd317bf398a017f7c690a475c5a67650c610323
PHP version: 8.2.6
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: CPlot

Error: Unhandled async exception: Implicit conversion from float -9.1546630859375 to int loses precision
File: plugins/CPlot_dev-development (2).phar/src/_e267b83df3ebb755c285_SOFe/AwaitGenerator/Await
Line: 587
Type: _e267b83df3ebb755c285_SOFe\AwaitGenerator\AwaitException
Backtrace:
#0 plugins/CPlot_dev-development (2).phar/src/_e267b83df3ebb755c285_SOFe/AwaitGenerator/Await(334): _e267b83df3ebb755c285_SOFe\AwaitGenerator\Await->reject(object ErrorException#358216)
#1 plugins/CPlot_dev-development (2).phar/src/_e267b83df3ebb755c285_SOFe/AwaitGenerator/Await(129): _e267b83df3ebb755c285_SOFe\AwaitGenerator\Await->wakeup(object Closure#612831)
#2 plugins/CPlot_dev-development (2).phar/src/ColinHDev/CPlot/commands/AsyncSubcommand(13): _e267b83df3ebb755c285_SOFe\AwaitGenerator\Await::g2c(object Generator#176898)
#3 plugins/CPlot_dev-development (2).phar/src/ColinHDev/CPlot/commands/PlotCommand(133): ColinHDev\CPlot\commands\AsyncSubcommand->execute(object pocketmine\player\Player#181670, array[0])
#4 pmsrc/src/command/SimpleCommandMap(212): ColinHDev\CPlot\commands\PlotCommand->execute(object pocketmine\player\Player#181670, string[1] p, array[0])
#5 pmsrc/src/Server(1415): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#181670, string[7] p merge)
#6 pmsrc/src/player/Player(1503): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#181670, string[7] p merge)
#7 pmsrc/src/network/mcpe/handler/InGamePacketHandler(818): pocketmine\player\Player->chat(string[8] /p merge)
#8 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#340683)
#9 pmsrc/src/network/mcpe/NetworkSession(437): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#147673)
#10 pmsrc/src/network/mcpe/NetworkSession(381): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#340683, string[30] M./p merge.LH4DR.eg...h%.....D)
#11 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[33] ..../P.M-JOe..0q..........#|3..\.)
#12 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[42] ..i.SK.dh~yR4tT....C..l..o...._..$M....L..)
#13 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#163488)
#14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#15 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#17 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1686740512.5848)
#18 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
#19 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[17] /home/CyberCraft/, string[25] /home/CyberCraft/plugins/)
#20 pmsrc/src/PocketMine(357): pocketmine\server()
#21 pmsrc(11): require(string[61] phar:///home/CyberCraft/PocketMine-MP.phar/src/PocketMine.php)

Code:
[578] 		$this->sleeping = true;
[579] 
[580] 		parent::reject($throwable);
[581] 		foreach($this->catches as $class => $onError){
[582] 			if($class === "" || is_a($throwable, $class)){
[583] 				$onError($throwable);
[584] 				return;
[585] 			}
[586] 		}
[587] 		throw new AwaitException("Unhandled async exception: {$throwable->getMessage()}", 0, $throwable);
[588] 	}
[589] 
[590] 	/**
[591] 	 * @internal This is implementation detail. Existence, signature and behaviour are semver-exempt.
[592] 	 */
[593] 	public function isSleeping() : bool{
[594] 		return $this->sleeping;
[595] 	}
[596] }

**Comment by ColinHDev** [comment] 2023-06-15 22:58
Please use separate issues next time, so the discussions get not mixed up.
- Can't produce the crash on /p visit
- The error with the update blocks through /p clear, /p reset, /p merge should be fixed as of 30c909c6bfa058e7be717046741427d1d88a1fcf
- The error with /p border, /p wall is fixed as of c4c6171ffe6261de886318ceb6c3623af89ae51b
- The error with command aliases is fixed as of 8512dd4888e9122048d3af8a7ef57a6649651c2b
- The error with /p merge is fixed as of 7777e5d69f02b610b0de820a2a9cedcf88916d49

**Comment by note3crafter** [comment] 2023-06-16 04:30
I make later a video whit /p visit...

**Comment by note3crafter** [comment] 2023-06-16 09:15
Newest Version of CPlot but whem i try /p h than will it crash

PocketMine-MP Crash Dump Fri Jun 16 11:14:02 CEST 2023

PocketMine-MP version: 5.1.2 [Protocol 589]
Git commit: 7cd317bf398a017f7c690a475c5a67650c610323
PHP version: 8.2.6
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: CPlot

Error: Unhandled async exception: Position world is null or has been unloaded
File: plugins/CPlot_dev-development (3).phar/src/_30deffc7e3dcebf24316_SOFe/AwaitGenerator/Await
Line: 587
Type: _30deffc7e3dcebf24316_SOFe\AwaitGenerator\AwaitException
Backtrace:
#0 plugins/CPlot_dev-development (3).phar/src/_30deffc7e3dcebf24316_SOFe/AwaitGenerator/Await(334): _30deffc7e3dcebf24316_SOFe\AwaitGenerator\Await->reject(object pocketmine\utils\AssumptionFailedError#192526)
#1 plugins/CPlot_dev-development (3).phar/src/_30deffc7e3dcebf24316_SOFe/AwaitGenerator/Await(317): _30deffc7e3dcebf24316_SOFe\AwaitGenerator\Await->wakeup(object Closure#192577)
#2 plugins/CPlot_dev-development (3).phar/src/_30deffc7e3dcebf24316_SOFe/AwaitGenerator/Await(552): _30deffc7e3dcebf24316_SOFe\AwaitGenerator\Await->wakeupFlat(object Closure#192577)
#3 plugins/CPlot_dev-development (3).phar/src/_30deffc7e3dcebf24316_SOFe/AwaitGenerator/AwaitChild(52): _30deffc7e3dcebf24316_SOFe\AwaitGenerator\Await->recheckPromiseQueue(object _30deffc7e3dcebf24316_SOFe\AwaitGenerator\AwaitChild#192544)
#4 plugins/CPlot_dev-development (3).phar/src/_30deffc7e3dcebf24316_SOFe/AwaitGenerator/Await(570): _30deffc7e3dcebf24316_SOFe\AwaitGenerator\AwaitChild->resolve(object ColinHDev\CPlot\plots\Plot#192546)
#5 plugins/CPlot_dev-development (3).phar/src/_30deffc7e3dcebf24316_SOFe/AwaitGenerator/Await(340): _30deffc7e3dcebf24316_SOFe\AwaitGenerator\Await->resolve(object ColinHDev\CPlot\plots\Plot#192546)
#6 plugins/CPlot_dev-development (3).phar/src/_30deffc7e3dcebf24316_SOFe/AwaitGenerator/Await(317): _30deffc7e3dcebf24316_SOFe\AwaitGenerator\Await->wakeup(object Closure#192568)
#7 plugins/CPlot_dev-development (3).phar/src/_30deffc7e3dcebf24316_SOFe/AwaitGenerator/Await(552): _30deffc7e3dcebf24316_SOFe\AwaitGenerator\Await->wakeupFlat(object Closure#192568)
#8 plugins/CPlot_dev-development (3).phar/src/_30deffc7e3dcebf24316_SOFe/AwaitGenerator/AwaitChild(52): _30deffc7e3dcebf24316_SOFe\AwaitGenerator\Await->recheckPromiseQueue(object _30deffc7e3dcebf24316_SOFe\AwaitGenerator\AwaitChild#192540)
#9 plugins/CPlot_dev-development (3).phar/src/_6d5df5ff8fbed9d79d67_poggit/libasynql/base/DataConnectorImpl(197): _30deffc7e3dcebf24316_SOFe\AwaitGenerator\AwaitChild->resolve(array[0])
#10 plugins/CPlot_dev-development (3).phar/src/_6d5df5ff8fbed9d79d67_poggit/libasynql/base/DataConnectorImpl(174): _6d5df5ff8fbed9d79d67_poggit\libasynql\base\DataConnectorImpl::_6d5df5ff8fbed9d79d67_poggit\libasynql\base\{closure}(array[0], array[0])
#11 plugins/CPlot_dev-development (3).phar/src/_6d5df5ff8fbed9d79d67_poggit/libasynql/base/DataConnectorImpl(181): _6d5df5ff8fbed9d79d67_poggit\libasynql\base\DataConnectorImpl::_6d5df5ff8fbed9d79d67_poggit\libasynql\base\{closure}(object _6d5df5ff8fbed9d79d67_poggit\libasynql\result\SqlSelectResult#192557)
#12 plugins/CPlot_dev-development (3).phar/src/_6d5df5ff8fbed9d79d67_poggit/libasynql/base/DataConnectorImpl(239): _6d5df5ff8fbed9d79d67_poggit\libasynql\base\DataConnectorImpl::_6d5df5ff8fbed9d79d67_poggit\libasynql\base\{closure}(array[1])
#13 plugins/CPlot_dev-development (3).phar/src/_6d5df5ff8fbed9d79d67_poggit/libasynql/base/SqlThreadPool(111): _6d5df5ff8fbed9d79d67_poggit\libasynql\base\DataConnectorImpl->_6d5df5ff8fbed9d79d67_poggit\libasynql\base\{closure}(array[1])
#14 plugins/CPlot_dev-development (3).phar/src/_6d5df5ff8fbed9d79d67_poggit/libasynql/base/DataConnectorImpl(322): _6d5df5ff8fbed9d79d67_poggit\libasynql\base\SqlThreadPool->readResults(array[1])
#15 plugins/CPlot_dev-development (3).phar/src/_6d5df5ff8fbed9d79d67_poggit/libasynql/base/SqlThreadPool(64): _6d5df5ff8fbed9d79d67_poggit\libasynql\base\DataConnectorImpl->checkResults()
#16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): _6d5df5ff8fbed9d79d67_poggit\libasynql\base\SqlThreadPool->_6d5df5ff8fbed9d79d67_poggit\libasynql\base\{closure}()
#17 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#18 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#19 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1686906842.7372)
#20 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
#21 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[17] /home/CyberCraft/, string[25] /home/CyberCraft/plugins/)
#22 pmsrc/src/PocketMine(357): pocketmine\server()
#23 pmsrc(11): require(string[61] phar:///home/CyberCraft/PocketMine-MP.phar/src/PocketMine.php)

Code:
[578] 		$this->sleeping = true;
[579] 
[580] 		parent::reject($throwable);
[581] 		foreach($this->catches as $class => $onError){
[582] 			if($class === "" || is_a($throwable, $class)){
[583] 				$onError($throwable);
[584] 				return;
[585] 			}
[586] 		}
[587] 		throw new AwaitException("Unhandled async exception: {$throwable->getMessage()}", 0, $throwable);
[588] 	}
[589] 
[590] 	/**
[591] 	 * @internal This is implementation detail. Existence, signature and behaviour are semver-exempt.
[592] 	 */
[593] 	public function isSleeping() : bool{
[594] 		return $this->sleeping;
[595] 	}
[596] }

Loaded plugins:
CPlot development by ColinHDev for API(s) 5.0.0

**Comment by ColinHDev** [comment] 2023-06-16 09:47
/p h is just an alias of /p visit, whose error I am not able to reproduce

**Closed as completed** 2023-06-16 13:39 UTC
Labels: Status: Completed, Category: UI, Category: Core, Type: Bug Report
