### ISSUE TITLE
Participating in Hacktoberfest

### ISSUE THREAD

**Issue by ColinHDev** [ColinHDev/CPlot#62] opened 2022-10-10 18:03 UTC
I added the [`Hacktoberfest`](https://hacktoberfest.com/) topic to the repository, so if anybody is interested in that, feel free to contribute.

**Comment by inxomnyaa** [comment] 2022-10-29 16:49
The event is almost over, haven't discovered the repo on time. Yet i wanted to ask if you would mind [MagicWE2](https://github.com/thebigsmileXD/MagicWE2/) integration in CPlot. I've created something similar for MyPlot a long time ago: [MWEEMyPlot](https://github.com/thebigsmileXD/MWEEMyPlot) 
As i am not familiar with the code of CPlot yet, i'd like to ask about some things first:
- If it were to be added, should it be coded as an "addon"?
- Are there any existing events or handlers that allow checking for build permissions in plots?
- Is building on roads allowed at all, and are those checks different from the above?
- Are there ways to get the boundaries (maybe AABB) of a plot?
- Should multi-plot edits be allowed? If so, only for aligned plots?
- Can plots be merged, and could there be conflicts with anything of the above caused by that?

**Comment by ColinHDev** [comment] 2022-10-29 21:44
- Looks like a made it confusing. "Addon" is only a fancy name for "a plugin which depends on CPlot". They are not different from any other plugin except they just don't load if CPlot is not present. (Just a simple `depend: CPlot` in the plugin.yml)
- There are not really any good API methods at the moment except for those used in the listeners: <https://github.com/ColinHDev/CPlot/blob/development/src/ColinHDev/CPlot/listener/BlockPlaceListener.php#L41-L51>
Although, I am of course open to merging any improvements other developers make to the API.
- "Is building on roads allowed at all": Well, that is up to the server owner, if they decide that everyone should be able to build there.
"Are those checks different from the above": CPlot uses an asynchronous database design, so there is no simple `getPlotByPosition() : Plot` method. There are `CPlotAPI::getOrLoadPlotAtPosition()` and `Plot::isOnPlot()` methods.
- There are no limits on how plots can be merged, e.g. a donut shape. So there is no `Plot::getAABB()` method
- What do you mean with "multi-plot edits"?
- Yes, plots can be merged into non-rectangular shapes.

**Comment by inxomnyaa** [comment] 2022-10-30 08:29
- Which means the "Addon" would function the same way as MWE2 addons, neat
- Multi plot edits would mean selecting pos1 in one plot, and pos2 in another, and allowing edits in all the blocks in between with build perms

The async methods might cause issues with MWE2's event handling, as it is not "waiting" for a method outcome
Does the plot merging combine multiple plots into one Plot object?
I guess for a basic version i could just copy the code from the BlockPlaceListener in order to handle selections. Having no distinct allowed shapes might complicate things

**Comment by ColinHDev** [comment] 2022-10-30 12:03
That would be up to you whether you want to allow multi-plot edits. It would be up to you to check if the player has build permissions inside all areas of the selection.

Since I also needed to handle PocketMine-MP's events, I had to figure something out to make the async database design work with the sync event handling:
```php
$plot = $this->getAPI()->getOrLoadPlotAtPosition($position)->getResult();
```
While `getOrLoadPlotAtPosition()` returns a `Promise`, it might already have a result if data about the plot is cached. If this is the case, the `getResult()` method returns the cached data or `null` otherwise. If no data is cached, the event is cancelled. (A query is run in the background, so the next time the event is called, the data might be already in the cache.)
This is used in all the event listeners, so you could use the same.

When plots are merged, one plot is the "origin plot", while all others are only considered "merge plots".
So, if you call e.g. the `isOnPlot()` method on a plot instance, you can be sure that it also checks all the merged plots and the roads in between.

I didn't put a lot of thought into this, but I'm not sure if it really complicates things. The only thing you would have to do is verify if a player has build permissions throughout all areas of the selection and skip sections if otherwise.

**Closed as completed** 2022-11-04 20:14 UTC
Labels: Category: Announcement
