### ISSUE TITLE
Setowner and give

### ISSUE THREAD

**Issue by ChaoscrafterZ** [ColinHDev/CPlot#53] opened 2022-08-06 12:20 UTC
Hey could you add /p setowner and /p give I know a lot of people want that and it would be nice if you add that

(/p give = give plot to player as user perm)

(/p setowner = plot to override a player Admin Perm)

**Comment by ColinHDev** [comment] 2022-08-06 12:28
duplicate of #45

**Closed as completed** 2022-08-06 12:28 UTC
Labels: Status: Duplicate
